### ISSUE TITLE
Dodać opcje usunięcia opinii - backend

### ISSUE THREAD

**Issue by Szczepaniak-M** [akai-org/AKAI-bookcrossing#38]
Stworzyć odpowiednie zapytanie SQL, funkcje w Dao oraz endpoint
Pamiętać o tym, że nie można usunąć nieswojej opinii

**Comment by dawids21** [comment]
Pójdę za ciosem i to też zaimplementuję.

**Comment by Szczepaniak-M** [comment]
Zrobiłem duży refactor, więc upewnij się że masz moje zmiany
